site_name: Gökhan Özen
theme:
  name: material
  language: tr
  custom_dir: overrides
  favicon: https://gokhanozen.top/plus/favicon.ico
  icon:
    logo: fontawesome/solid/hat-cowboy
  features: 
    - content.code.annotate 
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
       icon: material/weather-sunny
       name: Siyah Tema
      
    - scheme: default
      primary: blue
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Siyah Tema

  plugins:
    - typeset
    - search
  markdown_extensions:
     - admontion
     - pymdownx.details
     - pymdownx.superfences
     - attr_list
     - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
     - toc:
        permalink: true
  
copyright: Telif Hakları &copy; 2024 Gökhan Özen

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/gokhazen
    - icon: fontawesome/brands/twitter
      link: https://x.com/gokhazen
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/gokhazen/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@gokhazen

nav:
  - Anasayfa: http://127.0.0.1:8000/
  - Dokümantasyon:
      - 'Başlangıç': merhaba.md
      - 'Ubuntu Server Kurulum Rehberi':
        - 'Basit Linux Komutları': os/basitkomutlar.md
        - 'Statik Ip Belirleme': os/ubuntustaticip.md
        - 'Docker Kurulumu': os/dockerkurulumu.md
        - 'Diskin Tamamını Kullanma': os/fulldisk.md
        - 'Swap Ram Oluşturma': os/makeswap.md
        - 'Yeni Bir Disk Ekleme': os/seconddisk.md
        - 'Bios a Yeniden Başlatma': os/biosreboot.md
        - 'Flash Bellek Bağlama': os/usbdisk.md
      - 'Docker Projeleri':
        - 'Dockge': docker/dockge.md
        - 'Webtop': docker/webtop.md
        - 'FreshRSS': docker/freshrss.md
        - 'Uptime Kuma': docker/uptimekuma.md
        - 'Vaultwarden': docker/vaultwarden.md
        - 'Jellyfin': docker/jellyfin.md
        - '': docker/.md 
  - Projeler:
      - 'Başlangıç': projeler/merhaba.md
      - 'Yaratıcılığım':
        - 'Anderson Hosting API': projeler/andersonapi.md
        - 'Deprem Bilgi Sistemi': projeler/depremsitesi.md
        - 'Uygulama Mağazası': projeler/appstore.md
        - 'Lucy Discord Bot': projeler/lucydiscordbot.md
        - 'VideoCUT Klip Sistemi': projeler/videocut.md
        - 'Dürüm Bot': projeler/durumbot.md
  - Discord: https://gokhanozen.top/discord
  - Instagram: https://www.instagram.com/gokhazen/
  - Galeri: https://lucy.gokhanozen.top/art